name: CI
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  ci:
    uses: dv-flow/dv-flow-release/.github/workflows/dv-flow-pybuild.yml@main
    with:
        version_dir: "src/dv_flow/libide"
        tests_dir: "tests"
        build_docs: true
        run_tests: false
        pythonpath: "$(pwd)/src"
    secrets:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}


